/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.tutorial

class App {
    val greeting: String
        get() {
            return "Hello World!"
        } // method extendsion
}

fun main() {
    println(App().greeting)

    println("belajar gradle")

}
