/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.tutorial

import com.google.gson.Gson

class App {
    val greeting: String
        get() {
            return "Hello World!"
        } // method extendsion
}

fun main() {
    println(App().greeting)

    println("belajar gradle")

    val gson = Gson() // use gson from dependency

}
