/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.5/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.jvm)
//    kotlin("jvm") version "1.9.22"

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

group = "anak.om.mamat"
version = "0.0.1-SNAPSHOT"

repositories {
    // Use Maven Central for resolving dependencies... source dwonload repository dependency
    mavenCentral() // Apache Maven
    // jcenter() // Bintaray JCenter
    // google() // Google Android
}

dependencies {
    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    // Add dependency
    // implementation(Group-Dependency:Artifact:Version)
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.9")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.9")
    implementation("com.google.code.gson:gson:2.10.1")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("com.tutorial.AppKt")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

// custome tasks di gradle
// ./gradlew helloworld
tasks.register("helloworld"){
    doFirst {
        println("hello")
    }
    doLast {
        println("world")
    }
}

// menggunakan gradle properties
// ./gradlew author
tasks.register("author"){
    val author: String by project
    val email: String by project

    doLast {
        println("Author $author : $email")
    }
}
